import { Geist, Geist_Mono,Poppins,Montserrat,Whisper } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/Navigation"; // Adjust path as needed

export  const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

export const whisper = Whisper({
    variable: "--font-whisper",
    weight: ['400'],
    subsets : ['latin'],
})

export const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const montserrat = Montserrat({
    variable:"--font-montserrat",
    subsets:['latin']
});

const metadata = {
    title: "Road To Heaven",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <Navigation />
        {children}
        </body>
        </html>
    );
}
